:doc:`/shop_plugins/allgemein`
    Allgemeine Informationen über das Plugin-System

:doc:`/shop_plugins/aufbau`
    Ordner- und Dateistruktur

:doc:`/shop_plugins/infoxml`
    Aufbau der ``info.xml``

:doc:`/shop_plugins/bootstrapping`
    Der Bootstrapping-Prozess im JTL-Shop 5.x

:doc:`/shop_plugins/variablen`
    Verfügbare Plugin-Variablen

:doc:`/shop_plugins/hooks`
    Allgemeines über Hooks im JTL-Shop

:doc:`/shop_plugins/hook_list`
    Liste alles Hooks des JTL-Shops

:doc:`/shop_plugins/container`
    Der "Dependency Injection Container" (ab JTL-Shop 5.x)

:doc:`/shop_plugins/cache`
    Umgang mit dem Objektcache im JTL-Shop

:doc:`/shop_plugins/mailing`
    Versenden von Emails

:doc:`/shop_plugins/portlets`
    Den OnPageComposer erweitern

:doc:`/shop_plugins/fehlercodes`
    Mögliche Fehlercodes bei der Plugininstallation

:doc:`/shop_plugins/profiling`
    Zeitmessung der Plugin-Ausführung während der Entwicklungsphase

:doc:`/shop_plugins/sicherheit`
    Programmierung von sicheren Plugins im JTL-Shop

:doc:`/shop_plugins/payment_plugins`
    Oder: "Wie man ein Payment-Plugin schreibt"

:doc:`/shop_plugins/short_checkout`
    Änderungen im Zusammenhang mit dem "*verkürzten Checkout*" ab Version 4.06

:doc:`/shop_plugins/hinweise`
    Allgemeine Hinweise |br|
    Tipps und Tricks zur Entwicklung von Plugins, insbesondere für JTL-Shop 4.x
