:doc:`/shop_programming_tips/contributing`
    Mitmachen beim Entwickeln von JTL-Shop

:doc:`/shop_programming_tips/alerts`
    Informationen über das Erzeugen von Alerts (Meldungen wie z.B. Fehler/Hinweise)

:doc:`/shop_programming_tips/notifications`
    Notifications im Backend erzeugen

:doc:`/shop_programming_tips/shopclass`
    Die zentrale Bedeutung der `Shop`-Klasse und ihre Benutzung

:doc:`/shop_programming_tips/pagination`
    Blättern durch lange Listen ermöglichen

:doc:`/shop_programming_tips/backend_filter`
    Anzuzeigende Daten im Backend eingrenzen

:doc:`/shop_programming_tips/debug`
    Debug-Informationen, Unterstützung bei der Entwicklung zur Laufzeit

:doc:`/shop_programming_tips/profiling`
    Zeitmessungen in der Entwicklungsphase

:doc:`/shop_programming_tips/botsessions`
    Erkennen von Crawler-Sessions

:doc:`/shop_programming_tips/config_tips`
    Konstanten der ``config.JTL-Shop.ini.php``

:doc:`/shop_programming_tips/breaking_changes`
    Upgrade Guidelines

:doc:`/shop_programming_tips/licensing`
    Lizenzen
