JTL-Shop nutzt die Template-Engine `Smarty <https://www.smarty.net/>`_.
Im Frontend kommen HTML5, `Bootstrap <http://getbootstrap.com/>`_ sowie `jQuery <https://jquery.com/>`_
und diverse jQuery-Plugins zum Einsatz.

Es stehen verschiedene Möglichkeiten für individuelle Templateanpassungen zur Verfügung, auf die in dieser
Dokumentation näher eingegangen werden soll. |br|
Zur zusätzlichen Unterstützung bei Templateanpassungen existiert auch das
JTL-Plugin ":doc:`JTL Debug </shop_programming_tips/debug>`".

:doc:`/shop_templates/jtl_templates`
    Allgemeine Informationen über die aktuellen JTL-Shop-Templates

:doc:`/shop_templates/structure`
    Informationen zur Ordner- und Dateistruktur des Templates, sowie zum Aufbau der ``template.xml``

:doc:`/shop_templates/eigenes_template`
    Child-Templates, "Der bevorzugte Weg zum eigenen Template"

:doc:`/shop_templates/template_settings`
    Die einzelnen Einstellungen des Templates genauer erklärt

:doc:`/shop_templates/eigenes_theme`
    Eigene individuelle Designs erstellen, per Stylesheets (CSS, LESS und SCSS)

:doc:`/shop_templates/theme_edit`
    Einfache Anpassungen von Farben und Abstände mittels Theme-Anpassungen |br|
    Hier werden die verschiedenen Methoden erklärt.

:doc:`/shop_templates/primary_color`
    Einstellen der primären Farbe des JTL-Shops

:doc:`/shop_templates/overlays`
    Artikel-Overlays (wie z.B. "Bestseller") selbst erstellen

:doc:`/shop_templates/short_checkout`
    Änderungen im Zusammenhang mit dem "*verkürzten Checkout*" ab Version 4.06

:doc:`/shop_templates/jquery_update`
    Hinweise zur neuen jQuery-Version 3.x ab Shop Version 5.0

:doc:`/shop_templates/tipps_tricks`
    Template How-To's und Best Practices
